oceanbase/obkv-table-client-go

- protocol/aggregation_single.go
- protocol/border_flag.go
- protocol/entity.go
- protocol/htable_filter.go
- protocol/query.go
- protocol/query_request.go
- protocol/query_response.go
- protocol/range.go
- protocol/stream_request.go
- protocol/stream_response.go
> add query stream protocol

- protocol/aggregation_single.go
- protocol/aggregation_single_test.go
- protocol/htable_filter.go
- protocol/htable_filter_test.go
- protocol/query.go
- protocol/query_and_mutate.go
- protocol/query_and_mutate_request.go
- protocol/query_and_mutate_request_test.go
- protocol/query_and_mutate_response.go
- protocol/query_and_mutate_response_test.go
- protocol/query_and_mutate_test.go
- protocol/query_request_test.go
- protocol/query_response.go
- protocol/query_response_test.go
- protocol/query_test.go
- protocol/range.go
- protocol/range_test.go
- protocol/stream_request.go
> add query and mutate protocol 

- example/query/query.go
> [Doc] query example

- client/option.go
- client/query.go
- client/query_result.go
- client/query_result_iterator.go
- example/query/query.go
- example/single_operation/delete.go
- example/single_operation/get.go
- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
> fix example table not match

- protocol/object_meta.go
- util/serialization.go
> encode decode optimize

- client/obclient.go
- client/query.go
Fix obQueryExecutor.
- Modify the visibility of obQueryExecutor.
- Modify the visibility of some function in obQueryExecutor.
Pass all tests.
N.A.
N.A.
> [Fix] QueryExecutor

- client/query.go
- protocol/border_flag.go
- test/query/query_zero_test.go
Fix the border flag in obNewRange.
Fix the border flag in obNewRange.
Pass all test except index tests and zero query test.
N.A.
N.A.
> [Fix] border flag

- client/client.go
- client/obbatch.go
- client/obclient.go
- client/option/batch_option.go
- protocol/batch_operation_request.go
- table/kv_mode.go
Impl batch option for batch operation.
Impl ObBatchOption.
Pass all tests except the test with index.
> [Feat] batch option

- client/aggregate_executor.go
- client/aggregate_result.go
- client/client.go
- client/obaggregate.go
- client/obclient.go
- client/option/operation_option.go
- client/option/query_option.go
- client/query.go
- client/table.go
- client/util.go
- client/util_test.go
- example/aggregate/aggregate.go
- example/auto_increment/auto_inc_not_rowkey.go
- example/auto_increment/auto_inc_rowkey.go
- example/filter_operation/insert.go
- protocol/aggregation_single.go
- protocol/aggregation_single_test.go
- protocol/query.go
- protocol/query_and_mutate.go
- test/aggregate/aggregate_test.go
- test/aggregate/all_test.go
- test/autoinc/all_test.go
- test/autoinc/auto_increment_not_rowkey_test.go
- test/autoinc/auto_increment_rowkey_test.go
- test/filter/filter_operation_test.go
[Feat] add impl for aggregate、 auto increment、 checkAndInsert. add demo
add impl and demo
Pass tests except for index-tests in 4.x
N.A
N.A
> [Feat] add impl for aggregate、 auto increment、 checkAndInsert. add demo

- example/aggregate/aggregate.go
- example/auto_increment/auto_inc_not_rowkey.go
- example/auto_increment/auto_inc_rowkey.go
- example/batch_operation/batch.go
Modify some documents.
Modify some documents.
N.A.
N.A.
N.A.
> [Doc] modify demo

- client/option/query_option.go
- client/query.go
- example/query/query.go
- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
Implement query filter.
Implement query filter.
Pass all tests except for index tests in 4.x.
N.A.
N.A.
> [Feat] impl query filter

- client/hfilter/hfilter.go
- client/option/batch_option.go
- client/option/query_option.go
- client/query.go
- example/batch_operation/batch.go
- example/query/query.go
- protocol/htable_filter.go
- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
- Support HBase Filter
- Modify batch option and query option
- Add option for HBase filter
- Implement methods to ser filter into package
- Rename some option
Pass all tests except for index tests in 4.x
The batch option and the query option are changed, users should use latest interface.
N.A.
> [Feat] support HFilter & modify option

- client/query_result_iterator.go
- example/query/query.go
- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
- Remove err in query close()
- Modify some query test cases\
- Modify query demo
- Remove err in query close()
- Modify some query test cases\
- Modify query demo
Pass all tests except for index tests.
N.A.
N.A.
> [Refactor] modify query & query tests & query demo

- client/client.go
- client/obclient.go
- client/query.go
- client/table.go
- route/location.go
- test/util.go
Support ODP in Go client.
Support ODP in Go client.
Pass single/filter tests. Batch and query tests are not supported by ODP now.
N.A.
N.A.
> [Feat] support ODP

- test/ttl/all_test.go
- test/ttl/ttl_test.go
> add ttl test

- test/autoinc/all_test.go
- test/autoinc/auto_increment_normal_not_fill_test.go
- test/autoinc/auto_increment_rowkey_fill_zero_test.go
- test/autoinc/auto_increment_rowkey_not_fill_test.go
- add auto increment test
- NA
- all tests
> add auto increment test

- client/obclient.go
- test/batch/batch_operation_test.go
- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
- test/util.go
- Add test cases for ODP single partition test
- Add test cases for ODP single partition test
- Fix some bugs
Pass all tests.
FullUserName must be written as **user_name@tenant_name#cluster_name** in ODP mode now.
N.A.
> [Test] odp async query tests

- test/query/query_hash_test.go
- test/query/query_key_test.go
- test/query/query_zero_test.go
- Tests for ODP query filter
- Tests for ODP query filter
Pass all tests
N.A.
N.A.
> [Test] odp query filter

- test/aggregate/aggregate_test.go
- test/autoinc/auto_increment_normal_fill_test.go
- test/autoinc/auto_increment_rowkey_fill_zero_test.go
- test/autoinc/auto_increment_rowkey_not_fill_test.go
- test/current_timestamp/all_test.go
- test/current_timestamp/current_timestamp_test.go
- test/generate_column/all_test.go
- test/generate_column/stored_generate_column_test.go
- test/generate_column/virtual_generate_column_test.go
- test/single/int32_table_test.go
- add generate column test and current_timestamp test
> add generate column test and current_timestamp test

- test/login/all_test.go
- test/login/login_test.go
- test one user use different database
> add login test

- test/single/all_test.go
- test/single/blob_table_test.go
- test/single/clob_table_test.go
> add lob test

- test/primary_key_order/all_test.go
- test/primary_key_order/primary_key_order_test.go
> add primary key order tests

- test/util.go
> add isOdpMode for test

- client/obclient.go
- client/table.go
- obkvrpc/connection.go
- obkvrpc/rpc_client.go
- protocol/payload.go
- protocol/payload_base.go
- util/util.go
Set actual Addr to error
Get Addr from connection and set into result/error/
> [Feat] set actual addr in err

- test/current_timestamp/current_timestamp_test.go
- update current_timestamp test
> update current_timestamp test

- test/aggregate/aggregate_test.go
- test/autoinc/all_test.go
- test/autoinc/auto_increment_normal_fill_nil_test.go
- test/autoinc/auto_increment_rowkey_fill_nil_test.go
- add auto increment fill nil test
> add auto increment fill nil test

- test/batch/batch_operation_test.go
- test/login/login_test.go
- test/nullable/all_test.go
- test/nullable/nullable_test.go
- test/query/all_test.go
- test/query/query_lob_test.go
- test/ttl/ttl_test.go
- add lob query test & add nullable test & add batch ttl test
> add lob query test & add nullable test & add batch ttl test

- route/sql_driver_test.go
- test/query/query_lob_test.go
> modify lob query test

- util/obversion.go
- User now could use ODP to access OBServer_CE
- Modify regex
> [Fix] CE login with ODP

- obkvrpc/connection.go
fix compile error caused by #129
> fix compile error

- error/error_code.go
> add error code name

- obkvrpc/connection_mgr.go
> should call wg.add before goroutine start

- client/obclient.go
- fix core dump when close client
> core dump when close client

- client/obbatch.go
- client/obclient.go
- protocol/error.go
- route/route_info.go
> batch adapt odp mode

- test/generate_column/all_test.go
- test/generate_column/virtual_generate_column_test.go
- add tests for complicated table
> add mixed test

- test/query/query_hash_test.go
- Fix table generated SQL
- Modify key table into hash table
> [Test] fix sql

- test/autoinc/auto_increment_normal_fill_test.go
- test/autoinc/auto_increment_normal_not_fill_test.go
- test/current_timestamp/current_timestamp_test.go
- test/error_message/error_message_test.go
fix increment/append operation with current_timestamp or auto_increment column test case failed
> fix test case failed

- obkvrpc/rpc_server.go
> fix rpc server do not stop when ReadRequest panic

- client/client.go
- client/obbatch.go
- client/obclient.go
- client/query.go
- protocol/constants.go
- table/kv_mode.go
> add redis entity_type

- client/obclient.go
- obkvrpc/connection.go
Some log information is modified to enhance the log tracing function.
> modify some logs

- client/obclient.go
fix print log failed caused by tableParam is nil
> fix panic caused by string is nil

- client/client.go
- log/logger.go
> fix logLevel cannot validate
